SELECT * FROM customer;

-- Questions:

-- 1) What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY gender


-- 2) Which customers used a discount and still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)


--3) What are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating)::numeric, 2) as average_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_rating DESC
LIMIT 5


-- 4) Compare the average purchase amounts b/w standard and express shipping 

SELECT ROUND(AVG(case when shipping_type = 'Standard' then purchase_amount end)::numeric, 2) as Standard_avg, ROUND(AVG(case when shipping_type = 'Express' then purchase_amount end)::numeric, 2) as Express_avg
FROM customer

-- or

SELECT shipping_type, ROUND(AVG(purchase_amount),2) as average_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type


-- 5) Do subscribed customers spend more? Compare average spend and total revenue b/w subscribers and non-subcribers?

SELECT subscription_status, COUNT(customer_id) as total_users, ROUND(AVG(purchase_amount),2) as average_amount, ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY subscription_status DESC


-- 6) Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased, ROUND(100.00*SUM(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5

-- If discount_rate for Hat = 50% then it indicates that, if 10 Hats were sold, then the discount was applied 50% of the time (i.e 5 times) 


-- 7) Segment customers into new, returning and loyal based on their total number of previous purchases and show the count of each segment.

	-- Here we need to define new, returning and loyal metric. If a customer's previous purchase count is 1 then they are new, similarly, 
	-- if the count is say 2-10, they are returning and if the count is >10, they are loyal customers.

SELECT count(case when previous_purchases = 1 then customer_id end) as new_customers, 
	   count(case when previous_purchases BETWEEN 2 AND 10 then customer_id end) as returning_customers,
	   count(case when previous_purchases >=11 then customer_id end) as loyal_customers
FROM customer

	   
-- 8) What are the top 3 most purchased products within each category?

SELECT category, item_purchased
FROM(
SELECT category, item_purchased, count(item_purchased) as cnt, rank() OVER (PARTITION BY category ORDER BY count(item_purchased) DESC) as rank
FROM customer
GROUP BY category, item_purchased) x
WHERE rank<=3


-- 9) Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

WITH cte as (
SELECT customer_id, subscription_status
FROM customer
WHERE customer_id IN (SELECT customer_id FROM customer WHERE previous_purchases>5)
)

SELECT subscription_status, count(customer_id) as count 
FROM cte
GROUP BY subscription_status

SELECT ROUND((100.00*SUM(case when subscription_status = 'Yes' then 1 end)/count(*)),2) as likely_to_subscribe,
		ROUND((100.00*SUM(case when subscription_status = 'No' then 1 end)/count(*)),2) as not_likely_to_subscribe
FROM cte


-- 10) What is the reveue contribution of each age group?

SELECT age_group, ROUND(100.00*SUM(purchase_amount)/(SELECT SUM(purchase_amount) FROM customer),2) as revenue_contribution
FROM customer
GROUP BY age_group
ORDER BY revenue_contribution DESC

		























